#!/bin/bash

# Creates roff/manpage files using a folder of markdown files.
# Run this script from the "maestro/man" folder.
# Requires markdown files in the "markdown" folder and puts output in folder "roff"

set -eu

SOURCE_FOLDER=$1/markdown
TARGET_FOLDER=$2
mkdir -p ${TARGET_FOLDER}

if ! [ -e venv/bin/activate ] ; then
	echo "NNNNNOOOOOOOOOOOOOOOOOOOOOOOOOO"
	exit 8
fi
source manvenv/bin/activate

# Convert all markdowns to roff
for markdown in `find $SOURCE_FOLDER -name "*.md"` ; do
    name=`basename $markdown`
    name=${name::-5}

    # Copy markdown to a temp file and append the footer.md to it.
    temp_markdown=$TARGET_FOLDER/$(basename $markdown)
    cp $markdown $temp_markdown
    cat $1/footer.md >> $temp_markdown

    echo "Converting markdown to man page for '$name'."
    python3 $1/mrkd.py $temp_markdown $TARGET_FOLDER/$name.1
    rm $temp_markdown
done

# Create README
SCRIPT_NAME=`basename "$0"`
echo "These roff files were generated by the script '$SCRIPT_NAME' from the maestro project. You probably shouldn't modify them - instead modify the markdown files they were generated from.
" >> $TARGET_FOLDER/README
git remote -v | grep origin >> $TARGET_FOLDER/README


echo
echo "Contents of '$TARGET_FOLDER':"
ls $TARGET_FOLDER
