stages:
  - build
  - test
  - install

variables:
  ORD_SOUMET_C: "40"
  ORD_SOUMET_T: "3600"
  ORD_SOUMET_TMPFS: "5G"
  ORD_SOUMET_CM: "100G"
  ORD_SOUMET_SHELL: "/bin/bash"


# build_tcl:
#   stage: build
#   script:
#     - cd src/tcl
#     - ./INSTALL.sh
#
# build_core:
#   stage: build
#   script:
#     - cd src/core
#     - make

build_cmake:
  stage: build
  script:
    - cd src/core
    - mkdir build
    - cd build
    - /home/phc001/miniconda3/bin/cmake .. -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/src/core
    - make
  artifacts:
    untracked: true

build_make:
  stage: build
  script:
    - cd src/core
    - make

test_cmake:
  stage: test
  script:
    - cd src/core/build
    - mkdir test_tmpdir
    - export TMPDIR=$PWD/test_tmpdir
    - make test

test_make:
  stage: test
  script:
    - cd src/core
    - make test

install:
  stage: install
  script:
    - cd src/core/build
    - make install

