stages:
  - build
  - test
  - install

variables:
  ORD_SOUMET_C: "40"
  ORD_SOUMET_T: "3600"
  ORD_SOUMET_TMPFS: "5G"
  ORD_SOUMET_CM: "100G"
  ORD_SOUMET_SHELL: "/bin/bash"

build_cmake:
  stage: build
  script:
    - cd src/core
    - mkdir build
    - cd build
    - export PATH=/home/phc001/miniconda3/bin:$PATH
    - export PATH=/opt/homebrew/bin:.:/Users/pcarphin/go/bin:/Users/pcarphin/fs/bin:/Users/pcarphin/.local/bin:/Users/pcarphin/.philconfig/utils:.:/opt/homebrew/bin:.:/Users/pcarphin/go/bin:/Users/pcarphin/fs/bin:/Users/pcarphin/.local/bin:/Users/pcarphin/.philconfig/utils:.:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/homebrew/bin:/Users/pcarphin/go/bin:/Users/pcarphin/fs/bin:/Users/pcarphin/.local/bin:/Users/pcarphin/.philconfig/utils:${PATH}
    - cmake .. -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/src/core
    - make
  artifacts:
    untracked: true

build_make:
  stage: build
  script:
    - cd src/core
    - make

test_all:
  stage: test
  script:
    - cd src/core/build
    - mkdir test_tmpdir
    - export TMPDIR=$PWD/test_tmpdir
    - make test

test_single:
  stage: test
  script:
    - set +o errexit
    - cd src/core/build
    - mkdir test_tmpdir
    - export TMPDIR=$PWD/test_tmpdir
    - ./test_nfs_functions

install:
  stage: install
  script:
    - cd src/core/build
    - make install
