stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - /home/phc001/miniconda3/bin/cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/install-site
    - make
    - export TMPDIR=$PWD
    - make check
    - make install

  artifacts:
    paths:
      - build/install-site

