all:
	$(MAKE) -C xflow/ssm clean
	$(MAKE) -C xflow/ssm

	$(MAKE) -C maestro-utils/ssm clean
	$(MAKE) -C maestro-utils/ssm

	$(MAKE) -C maestro-manager/ssm clean
	$(MAKE) -C maestro-manager/ssm

	$(MAKE) -C maestro-tcl/tcl-tk_8.5.11_multi/ssm clean
	$(MAKE) -C maestro-tcl/tcl-tk_8.5.11_multi/ssm

	./hare-compile.sh

	$(MAKE) -C maestro clean
	$(MAKE) -C maestro all

	./soft-link-ssm.sh

