all:
	$(MAKE) -C xflow/ssm clean
	$(MAKE) -C xflow/ssm

	$(MAKE) -C maestro-utils/ssm clean
	$(MAKE) -C maestro-utils/ssm

	$(MAKE) -C maestro-manager/ssm clean
	$(MAKE) -C maestro-manager/ssm

	$(MAKE) -C maestro-tcl/ssm clean
	$(MAKE) -C maestro-tcl/ssm

	$(MAKE) -C maestro-core clean
	$(MAKE) -C maestro-core

	./hare-compile.sh || exit 1
	./soft-link-ssm.sh || exit 1

