#!/bin/ksh
domainHome=$1
packageHome=$2
profileDirPath=${packageHome}/etc/profile.d
packageName=${packageHome##*/}
profilePath=${profileDirPath}/${packageName}.sh
mkdir -p ${profileDirPath}
Platform=`uname -s` ; [[ $Platform = Linux ]] && Platform=${Platform}-`uname -m`
cp ${packageHome}/.ssm.d/profile.sh ${profilePath}

BIN_FOLDER=${packageHome}/bin
TCL_SRC=${packageHome}/src/tcl
TCL_BIN_FOLDER=${packageHome}/tcl_bin
XM_SRC=${packageHome}/src/xm
 
# Soft link all bins to the root bin folder.
ln -s ${packageHome}/src/core/bin/* ${BIN_FOLDER}/
ln -s ${packageHome}/src/utilities/bin/* ${BIN_FOLDER}/
ln -s ${packageHome}/src/xflow/bin/* ${BIN_FOLDER}/
ln -s ${packageHome}/src/xm/bin/* ${BIN_FOLDER}/

# tcl bins go in a special bins folder, so that they do not clash with a possible system installable of tcl
ln -s ${packageHome}/src/tcl/bin ${TCL_BIN_FOLDER}

echo "export SEQ_PACKAGE_HOME=${packageHome}" >> ${profilePath}
echo "export SEQ_BIN=${BIN_FOLDER}" >> ${profilePath}
echo "export SEQ_TCL_BIN=${TCL_BIN_FOLDER}" >> ${profilePath}
echo "export SEQ_TCL_SRC=${TCL_SRC}" >> ${profilePath}
echo "export SEQ_MANAGER_BIN=${BIN_FOLDER}" >> ${profilePath}
echo "export SEQ_MANAGER_SRC=${XM_SRC}" >> ${profilePath}
echo "export SEQ_MANAGER_DOMAIN=${domainHome}" >> ${profilePath}
echo "export SEQ_UTILS_BIN=${BIN_FOLDER}" >> ${profilePath}
echo "export SEQ_UTILS_DOMAIN=${domainHome}" >> ${profilePath}
echo "export SEQ_XFLOW_BIN=${BIN_FOLDER}" >> ${profilePath}
echo "export SEQ_XFLOW_DOMAIN=${domainHome}" >> ${profilePath}

echo "export SEQ_MAESTRO_DOMAIN=${domainHome}" >> ${profilePath}
echo "export SEQ_MAESTRO_SHORTCUT=\". ssmuse-sh -d ${domainHome}\"" >> ${profilePath}
echo 'export TMPDIR=${TMPDIR:-/tmp/$USER/$$} && mkdir -p ${TMPDIR}' >> ${profilePath}
echo 'export TRUE_HOST=${TRUE_HOST:-$(hostname)}' >> ${profilePath}
chmod 644 ${profilePath}
