#!/bin/ksh
DOMAIN_HOME=$1
PACKAGE_HOME=$2
PROFILE_D=${PACKAGE_HOME}/etc/profile.d
PACKAGE_NAME=${PACKAGE_HOME##*/}
PROFILE_SCRIPT=${PROFILE_D}/${PACKAGE_NAME}.sh
mkdir -p ${PROFILE_D}
cp ${PACKAGE_HOME}/.ssm.d/profile.sh ${PROFILE_SCRIPT}

BIN_FOLDER=${PACKAGE_HOME}/bin
TCL_BIN_FOLDER=${PACKAGE_HOME}/tcl_bin
 
# Soft link all bins to the root bin folder.
ln -s ${PACKAGE_HOME}/src/core/bin/* ${BIN_FOLDER}/
ln -s ${PACKAGE_HOME}/src/utilities/bin/* ${BIN_FOLDER}/
ln -s ${PACKAGE_HOME}/src/xflow/bin/* ${BIN_FOLDER}/
ln -s ${PACKAGE_HOME}/src/xm/bin/* ${BIN_FOLDER}/

# tcl bins go in a special bins folder, so that they do not clash with a possible system installation of tcl
rm -f ${TCL_BIN_FOLDER}
ln -s ${PACKAGE_HOME}/src/tcl/bin ${TCL_BIN_FOLDER}

echo "
# Many of these values are duplicates for backwards compatibility.
# This happened after many projects and packages were consolidated into one.

export SEQ_PACKAGE_HOME=${PACKAGE_HOME}

export SEQ_BIN=${BIN_FOLDER}
export SEQ_MANAGER_BIN=${BIN_FOLDER}
export SEQ_XFLOW_BIN=${BIN_FOLDER}
export SEQ_UTILS_BIN=${BIN_FOLDER}
export SEQ_TCL_BIN=${TCL_BIN_FOLDER}

export SEQ_SRC=${PACKAGE_HOME}/src
export SEQ_MANAGER_SRC=${PACKAGE_HOME}/src/xm
export SEQ_TCL_SRC=${PACKAGE_HOME}/src/tcl

export SEQ_TCL_LIB=${PACKAGE_HOME}/src/tcl/lib

#this is the folder which contains the 'wrappers' folders
export SEQ_WRAPPERS=${PACKAGE_HOME}/src/core

export SEQ_MAESTRO_DOMAIN=${DOMAIN_HOME}
export SEQ_MANAGER_DOMAIN=${DOMAIN_HOME}
export SEQ_XFLOW_DOMAIN=${DOMAIN_HOME}
export SEQ_UTILS_DOMAIN=${DOMAIN_HOME}

export SEQ_MAESTRO_SHORTCUT=\". ssmuse-sh -d ${DOMAIN_HOME}\"
export TMPDIR=\${TMPDIR:-/tmp/\$USER/\$\$}
mkdir -p \${TMPDIR}
export TRUE_HOST=\${TRUE_HOST:-\$(hostname)}
export MANPATH=\$MANPATH:${PACKAGE_HOME}/man:

" >> ${PROFILE_SCRIPT}

chmod 644 ${PROFILE_SCRIPT}

