#!/bin/ksh
domainHome=$1
packageHome=$2

#check platform to see if compilation can be done. 
pkg=${packageHome##*/}
platform=${pkg##*_}

if [[ "${platform}" == ${ORDENV_PLAT} ]] ; then 
  echo "Compiling in place, this will take a while." 
  sleep 1
  cd $packageHome/src
  make clean
  make
else
  echo Platform ${platform} != ${ORDENV_PLAT}. Cannot compile. Please log on appropriate compilation host.
  exit 1
fi 
